[[local|localrc]]
LOGFILE=/opt/stack/logs/stack.sh.log
SCREEN_LOGDIR=~/screen_log/
LOGDAYS=1

ADMIN_PASSWORD=labstack
MYSQL_PASSWORD=mysql
RABBIT_PASSWORD=rabbit
SERVICE_PASSWORD=admin
SERVICE_TOKEN=service

MULTI_HOST=1
HOST_IP=192.168.42.12 #Change this for each compute node
HOST_NAME=$(hostname)
SERVICE_HOST=192.168.42.11 #Change this to your controller IP

MYSQL_HOST=$SERVICE_HOST
RABBIT_HOST=$SERVICE_HOST
GLANCE_HOSTPORT=$SERVICE_HOST:9292
KEYSTONE_AUTH_HOST=$SERVICE_HOST
KEYSTONE_SERVICE_HOST=$SERVICE_HOST

FLAT_INTERFACE=eth0
Q_PLUGIN=ml2
Q_ML2_TENANT_NETWORK_TYPE=vlan
Q_ML2_PLUGIN_TYPE_DRIVERS=vlan
ENABLE_TENANT_VLANS=True
PHYSICAL_NETWORK=default
TENANT_VLAN_RANGE=1000:1999

# TODO: Set disk driver details for your environment
# DISK_DRIVER: localdisk or ssp. localdisk requires VOL_GRP_NAME. Set to the
# volume group that will host the volume groups. Must not be rootvg.
DISK_DRIVER=localdisk
VOL_GRP_NAME=devstackvg

# Set to True to install the latest pypowervm from source
INSTALL_PYPOWERVM=False

NOVA_VNC_ENABLED=True
NOVNCPROXY_BASE_URL="http://$SERVICE_HOST:6080/vnc_auto.html"
VNCSERVER_LISTEN=$HOST_IP
VNCSERVER_PROXYCLIENT_ADDRESS=$VNCSERVER_LISTEN

# Set enabled services (pvm-q-agt and pvm-ceilometer-acompute started by their plugins)
ENABLED_SERVICES=n-cpu,neutron,n-api-meta

# Enable plugins
enable_plugin ceilometer https://git.openstack.org/openstack/ceilometer.git
enable_plugin nova-powervm https://git.openstack.org/openstack/nova-powervm.git
enable_plugin networking-powervm https://git.openstack.org/openstack/networking-powervm.git
enable_plugin ceilometer-powervm https://git.openstack.org/openstack/ceilometer-powervm.git

# Disable services
disable_service ceilometer-acentral ceilometer-collector ceilometer-api

[[post-config|$NOVA_CONF]]
[DEFAULT]
debug=False
default_log_levels=nova_powervm=DEBUG,nova=DEBUG,pypowervm=INFO,iamqplib=WARN,sqlalchemy=WARN,boto=WARN,suds=INFO,keystone=INFO,eventlet.wsgi.server=WARN
